# pull official base image
# FROM node:13.12.0-alpine
FROM node:latest

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
# ENV PATH /app/node_modules/.bin:$PATH

# add app
COPY ./client ./

RUN ls -a
RUN cat package.json
RUN pwd

# install app dependencies
RUN npm install 
RUN npm install -g serve
RUN npm build

# start app
# CMD ["npm", "start"]
EXPOSE 5000
CMD ["serve", "-s", "build"]

