# version: "3"
# services:
#     webapp:
#         build:
#             context: .
#             dockerfile: Dockerfile
#         ports:
#             - "8080:3000"
#         volumes:
#             - ./:/code/:ro

# "build": "npm build",
# "clean": "rm -rf node_modules", 
# "reinstall": "npm run clean && npm install", 
# "rebuild": "npm run clean && npm install && npm run build",

# PRODUCTION
version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-app
    ports:
      - "3001:3001"
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    ports:
      - "8080:3000"
    stdin_open: true